Flood_Fill/flood_fill.cpp
=> Add Flood Fill Algorithm

Dijikstra/dijikstra.cpp
=> Add Dijikstra Algorithm

Krushkal_Rank/krushkal_by_rank.cpp
=> Add Krushkal Algorithm

GaleShapley.cpp
I've implemented the Gale Shapley Stable Matching algorithm for matching n companies to n students in CPP where integers are used for representing a preference of companies and students.
=> Implemented Gale Shapley Stable matching Algorithm in cpp

FactorialBigIntegers.cpp
Fixes #27 
This program is able to calculate factorial of any number especially for integers greater 20.
=> Factorial Program

BinaryTree.cpp
Cpp program to insert element in binary tree
=> Binary Tree Insertion

DP/Longest Common Subsequence/LCS_bruteForce.cpp, DP/Longest Common Subsequence/LCS_optimized_DP.cpp
=> Added LCS #35

Binary Tree/heightBinaryTree.cpp, DP/kadane.cpp
=> Added kadane code in cpp

Sorting/HeapSort.cpp
=> created HeapSort algorithm in c++

Graph/Breadth_First_Search.cpp
Cpp code for breadth first search of a graph.
=> Breadth first search

DP/Longest Increasing Subsequence/main.cpp
added a standard Dynamic Programming Algorithm to find the length of Longest Increasing Algorithm
=> added Longest Increasing Subsequence Algorithm

Sorting/InsertionSort.cpp
Insertion sort of an array for an example array.
Array is already declared in the code.
=> implemented Insertion Sort

DP/CatalanNumber.java, DP/CoinExchangeProblem.java, DP/GoldMineProblem.java, DP/MatrixChainMultiplication.java, DP/MaximumSizeSquareSubMatrixWithAll1s.java, DP/MaximumSumSubArrayByRemovingAtMostOneElement.java, DP/MinEditsToConvertStr1ToStr2.java, DP/MinimumSumPartition.java, DP/MobileNumericKeypadProblem.java
Added various classic and famous DP algorithms implemented in Java 8.
=> Added DP Algorithms

Binary Tree/Check_MirrorTrees.cpp, Binary Tree/Reverse_Level_Order.cpp
C++ program to implement an algorithm for reverse-level-order-traversal in Binary Tree
=> add Reverse_level_order traversal in Binary tree

CONTRIBUTING.md, Codeforces problems/535B Tavas and SaDDas.cpp
Solution to codeforces 535B has been added
=> Added cf 535B

quickSort.cpp, rainWater.cpp
Added Rainwater trapping problem solution
=> Added one file

Stack/stack_using_array.c
Remind me if any corrections are needed!
=> added implementation of stack using array #91

Graph Theory/mst_kruskals.cpp
Issue #91 
Added MST Kruskal C++
=> Added MST Kruskals

TreeTraversals/Inordertraversal.java, TreeTraversals/PostOrderTraversal.java, TreeTraversals/PreOrderTraversal.java
Tree Traversals include Inorder traversal, Pre-order Traversal, and Post-order Traversal.
=> Add Tree Traversals to ds-algo

queue/queue_linkedlist.java
Kindly remind me if any further updation is needed
=> queue using linked list in java #91

fractional_knapsack.cpp
Please let me know if any changes are required
=> fractional knapsack

Codeforces problems/236ABoyOrGirl.cs
Pull request for solution for problem in code forces i.e. https://codeforces.com/problemset/problem/236/A
=> Solution to problem "Boy or Girl " problem

Searching/A_star_search.cpp
Added A* search algorithm in searching directory
=> Added A* search algorithm

CONTRIBUTING.md
I added A* search algorithm to repo
=> Add request as a contributor

DP/createMaximumNumber.cpp
Added Leetcode's problem Create Maximum Number solution
=> Created CreateMaximumNumber.cpp

DP/SuperEggDrop.cpp
LeetCode Problem Super Egg Drop Solution
=> Created SuperEggDrop.cpp

DP/KInversePairsArray.cpp
Added Leetcode Solution K Inverse Pairs Array
=> Created KInversePairsArray.cpp

Codechef Problems/WITBIT.cpp
Added Codechef - WITBIT solution.
=> Created WITBIT.cpp

DP/palindromePartitioning.cpp
Added Leetcode Palindrome Partitioning II.
=> Created Palindrome Partitioning II

DP/distinctSubsequences.cpp
Added the leetcode Distinct Subsequences solution.
=> distinctSubsequences.cpp
